name: Release

on: push

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: thedoctor0/zip-release@0.7.1
        with:
          filename: blur-disabler-magisk.zip
      - uses: ncipollo/release-action@v1
        with:
          artifacts: blur-disabler-magisk.zip
          bodyFile: CHANGELOG.md
          makeLatest: true
          allowUpdates: true
